---
- name: Run Containers
  hosts: localhost
  become: true
  tasks:
    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
      loop:
        - centos
        - kalilinux/kali-linux-docker
        - ubuntu
        - zorinos/core

    - name: Run Docker containers
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
      loop:
        - { name: "centos", image: "centos" }
        - { name: "kali", image: "kalilinux/kali-linux-docker" }
        - { name: "ubuntuserver", image: "ubuntu" }
        - { name: "zorin", image: "zorinos/core" }
