---
- name: Configure network settings
  hosts: all
  become: yes
  tasks:
    - name: Configure IP address
      ansible.builtin.command: ip addr add 192.168.1.100/24 dev eth0
      ignore_errors: yes

    - name: Set default gateway
      ansible.builtin.command: ip route add default via 192.168.1.1
      ignore_errors: yes

    - name: Configure DNS
      ansible.builtin.copy:
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
        dest: /etc/resolv.conf

    - name: Restart networking
      ansible.builtin.service:
        name: networking
        state: restarted
