---
- name: Install and enable sudo
  hosts: docker
  become: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: "'ubuntu' in inventory_hostname"

    - name: Install sudo
      package:
        name: sudo
        state: present

    - name: Ensure sudo group exists
      group:
        name: sudo
        state: present

    - name: Add user to sudo group
      user:
        name: root
        groups: sudo
        append: yes
      become: true

    - name: Ensure sudoers file allows sudo group
      lineinfile:
        path: /etc/sudoers
        line: '%sudo   ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
      become: true
