---
- name: Update and Upgrade all hosts
  hosts: linux
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes
      become: yes
      become_user: root
      become_method: sudo

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
      become: yes
      become_user: root
      become_method: sudo
